---
- name: Install smokeping packages
  apt: name={{ item }} state=present pdate_cache=yes cache_valid_time=3600
  with_items:
    - smokeping
    - curl
    - libauthen-radius-perl
    - libnet-ldap-perl
    - libnet-dns-perl
    - libio-socket-ssl-perl
    - libnet-telnet-perl
    - libsocket6-perl
    - libio-socket-inet6-perl
    - apache2

- name: Configure smokeping General file
  template: src=General.j2 dest=/etc/smokeping/config.d/General mode=0644

- name: Copy smokeping FPing probe
  copy: src=Probes dest=/etc/smokeping/config.d/Probes mode=0644

- name: Configure Apache virtualhost for smokeping
  template: src=smokeping.conf.j2 dest=/etc/apache2/sites-available/smokeping.conf

- name: Enable smokeping Apache virtualhosts
  file: src=/etc/apache2/sites-available/smokeping.conf dest=/etc/apache2/sites-enabled/smokeping.conf state=link
  notify: restart apache
