---
- name: Install smokeping packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - smokeping
    - curl
    - libauthen-radius-perl
    - libnet-ldap-perl
    - libnet-dns-perl
    - libio-socket-ssl-perl
    - libnet-telnet-perl
    - libsocket6-perl
    - libio-socket-inet6-perl
    - xmail
    - apache2

- name: Configure smokeping General
  template: src=General.j2 dest=/etc/smokeping/config.d/General mode=0644

- name: Configure smokeping Targets
  template: src=Targets.j2 dest=/etc/smokeping/config.d/Targets mode=0644
  with_items: targets

- name: Copy smokeping FPing probe
  copy: src=Probes dest=/etc/smokeping/config.d/Probes mode=0644
  notify: restart smokeping

- name: Enable Apache CGI module
  apache2_module: state=present name=cgid

# - name: Test copy apache2 config
#   command: /bin/cp /etc/smokeping/apache2.conf /etc/apache2/conf-available/smokeping.conf creates=/etc/apache2/conf-available/smokeping.conf
# 
# - name: Test enable smokeping apache config
#   command: /usr/sbin/a2enconf smokeping.conf creates=/etc/apache2/conf-enabled/smokeping.conf
#   notify: restart apache

- name: Configure Apache virtualhost for smokeping
  template: src=smokeping.conf.j2 dest=/etc/apache2/sites-available/smokeping.conf

- name: Enable smokeping Apache virtualhosts
  file: src=/etc/apache2/sites-available/smokeping.conf dest=/etc/apache2/sites-enabled/smokeping.conf state=link
  notify: restart apache
